on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:

    continue-on-error: true
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: .\Scripts\Parse-AzureSustainabilityData.ps1
      shell: pwsh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'New version of regiondata'
        branch: 'refs/heads/newbranch'
    - uses: rematocorp/open-pull-request-action@v1
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        from-branch: newbranch
        to-branch: main
        repository-owner: autosysops
        repository: azure_sustainability_data