on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  ParseData:

    continue-on-error: true
    runs-on: windows-latest

    steps:
    - name: Check out main branch
      uses: actions/checkout@v1
    - name: Get data from azure globe
      run: |
        ./Scripts/Parse-AzureSustainabilityData.ps1
      shell: pwsh
    - name: commit changes to new branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'New version of regiondata'
        branch: 'refs/heads/newbranch'
    - name: create pull request
      uses: rematocorp/open-pull-request-action@v1
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        from-branch: newbranch
        to-branch: main
        repository-owner: autosysops
        repository: azure_sustainability_data